In [1]:
import pandas as pd
import numpy as np
from astropy.utils.console import ProgressBar

from tqdm import tqdm_notebook as tqdm

from matplotlib import pyplot as plt
%matplotlib inline

In [2]:
df_selected = pd.read_hdf('media/selected.hdf5', key='selection3')

In [8]:
df_selected = df_selected.sort_values(by=['mass_bin', 'dnf_bin'])

In [9]:
row_template = (
"""
<tr>
  <th scope="row">{num:d}</th>
  <td>{rockstarID:d}</td>
  <td>{mvir:.1e}</td>
  <td>{rvir:.1f}</td>
  <td>{dnf:.1f}</td>
  <td>{massbin:d}</td>
  <td>{dnfbin:d}</td>
</tr>
"""
)

In [10]:
text = ''

for i in range(len(df_selected)):
    row = df_selected.iloc[i]
    
    row_text = row_template.format(
        num=i+1,
        rockstarID=row.name,
        rvir=row.rvir,
        mvir=row.mvir,
        dnf=row.dnf,
        massbin=int(row.mass_bin),
        dnfbin=int(row.dnf_bin),
    )
    
    text += row_text
    
print(text)

<tr>
  <th scope="row">1</th>
  <td>147804</td>
  <td>1.1e+11</td>
  <td>96.2</td>
  <td>6.5</td>
  <td>1</td>
  <td>1</td>
</tr>

<tr>
  <th scope="row">2</th>
  <td>33296</td>
  <td>1.3e+11</td>
  <td>103.6</td>
  <td>9.2</td>
  <td>1</td>
  <td>2</td>
</tr>

<tr>
  <th scope="row">3</th>
  <td>95915</td>
  <td>2.0e+11</td>
  <td>117.9</td>
  <td>13.2</td>
  <td>1</td>
  <td>3</td>
</tr>

<tr>
  <th scope="row">4</th>
  <td>116774</td>
  <td>1.1e+11</td>
  <td>96.7</td>
  <td>28.3</td>
  <td>1</td>
  <td>4</td>
</tr>

<tr>
  <th scope="row">5</th>
  <td>241738</td>
  <td>1.3e+11</td>
  <td>103.0</td>
  <td>44.7</td>
  <td>1</td>
  <td>5</td>
</tr>

<tr>
  <th scope="row">6</th>
  <td>124717</td>
  <td>3.5e+11</td>
  <td>143.1</td>
  <td>5.7</td>
  <td>2</td>
  <td>1</td>
</tr>

<tr>
  <th scope="row">7</th>
  <td>33306</td>
  <td>2.8e+11</td>
  <td>131.9</td>
  <td>11.6</td>
  <td>2</td>
  <td>2</td>
</tr>

<tr>
  <th scope="row">8</th>
  <td>206641</td>
  <td>2.2e+11</td>
  <td>122.2</td>
  <td>12.4</td>
  <td>2</td>
  <td>3</td>
</tr>

<tr>
  <th scope="row">9</th>
  <td>229533</td>
  <td>2.8e+11</td>
  <td>131.8</td>
  <td>22.0</td>
  <td>2</td>
  <td>4</td>
</tr>

<tr>
  <th scope="row">10</th>
  <td>124429</td>
  <td>3.5e+11</td>
  <td>142.3</td>
  <td>57.5</td>
  <td>2</td>
  <td>5</td>
</tr>

<tr>
  <th scope="row">11</th>
  <td>32879</td>
  <td>6.8e+11</td>
  <td>178.2</td>
  <td>6.7</td>
  <td>3</td>
  <td>1</td>
</tr>

<tr>
  <th scope="row">12</th>
  <td>70495</td>
  <td>6.0e+11</td>
  <td>170.9</td>
  <td>9.3</td>
  <td>3</td>
  <td>2</td>
</tr>

<tr>
  <th scope="row">13</th>
  <td>51769</td>
  <td>6.0e+11</td>
  <td>171.0</td>
  <td>11.9</td>
  <td>3</td>
  <td>3</td>
</tr>

<tr>
  <th scope="row">14</th>
  <td>147062</td>
  <td>9.2e+11</td>
  <td>196.8</td>
  <td>20.5</td>
  <td>3</td>
  <td>4</td>
</tr>

<tr>
  <th scope="row">15</th>
  <td>136254</td>
  <td>6.7e+11</td>
  <td>177.5</td>
  <td>43.1</td>
  <td>3</td>
  <td>5</td>
</tr>

<tr>
  <th scope="row">16</th>
  <td>136001</td>
  <td>1.0e+12</td>
  <td>205.6</td>
  <td>6.3</td>
  <td>4</td>
  <td>1</td>
</tr>

<tr>
  <th scope="row">17</th>
  <td>206312</td>
  <td>1.1e+12</td>
  <td>208.0</td>
  <td>9.6</td>
  <td>4</td>
  <td>2</td>
</tr>

<tr>
  <th scope="row">18</th>
  <td>79392</td>
  <td>1.1e+12</td>
  <td>208.2</td>
  <td>14.9</td>
  <td>4</td>
  <td>3</td>
</tr>

<tr>
  <th scope="row">19</th>
  <td>193602</td>
  <td>1.0e+12</td>
  <td>203.4</td>
  <td>21.0</td>
  <td>4</td>
  <td>4</td>
</tr>

<tr>
  <th scope="row">20</th>
  <td>1330</td>
  <td>1.0e+12</td>
  <td>203.3</td>
  <td>36.3</td>
  <td>4</td>
  <td>5</td>
</tr>

<tr>
  <th scope="row">21</th>
  <td>146616</td>
  <td>3.5e+12</td>
  <td>306.6</td>
  <td>5.7</td>
  <td>5</td>
  <td>1</td>
</tr>

<tr>
  <th scope="row">22</th>
  <td>123930</td>
  <td>3.9e+12</td>
  <td>319.9</td>
  <td>10.0</td>
  <td>5</td>
  <td>2</td>
</tr>

<tr>
  <th scope="row">23</th>
  <td>193262</td>
  <td>2.5e+12</td>
  <td>274.1</td>
  <td>15.5</td>
  <td>5</td>
  <td>3</td>
</tr>

<tr>
  <th scope="row">24</th>
  <td>135915</td>
  <td>2.4e+12</td>
  <td>272.5</td>
  <td>20.5</td>
  <td>5</td>
  <td>4</td>
</tr>

<tr>
  <th scope="row">25</th>
  <td>181619</td>
  <td>2.2e+12</td>
  <td>264.4</td>
  <td>35.3</td>
  <td>5</td>
  <td>5</td>
</tr>

<tr>
  <th scope="row">26</th>
  <td>157850</td>
  <td>5.1e+12</td>
  <td>348.2</td>
  <td>5.7</td>
  <td>6</td>
  <td>1</td>
</tr>

<tr>
  <th scope="row">27</th>
  <td>240613</td>
  <td>6.8e+12</td>
  <td>383.2</td>
  <td>8.8</td>
  <td>6</td>
  <td>2</td>
</tr>

<tr>
  <th scope="row">28</th>
  <td>146457</td>
  <td>5.0e+12</td>
  <td>345.8</td>
  <td>13.0</td>
  <td>6</td>
  <td>3</td>
</tr>

<tr>
  <th scope="row">29</th>
  <td>21720</td>
  <td>6.3e+12</td>
  <td>374.9</td>
  <td>21.5</td>
  <td>6</td>
  <td>4</td>
</tr>

In [3]:
df_selected

,count_n,dnf,dnf_bin,hid,mass_bin,mvir,nn_bin,np,rvir,x,y,z
hid,,,,,,,,,,,,
33296,35.0,9.191305,2.0,33296.0,1.0,1.339000e+11,2.0,NaN,103.629,15.19173,22.11955,47.41179
95915,12.0,13.153042,3.0,95915.0,1.0,1.970000e+11,1.0,NaN,117.862,8.95348,46.30461,31.73776
116774,15.0,28.275509,4.0,116774.0,1.0,1.086000e+11,1.0,NaN,96.651,24.64649,12.45386,4.11703
241738,9.0,44.698071,5.0,241738.0,1.0,1.315000e+11,1.0,NaN,102.990,47.14500,40.70770,45.55846
33306,30.0,11.565937,2.0,33306.0,2.0,2.760000e+11,2.0,NaN,131.884,10.26344,2.99136,42.59729
206641,19.0,12.365766,3.0,206641.0,2.0,2.194000e+11,1.0,NaN,122.169,44.76641,39.79041,14.08442
229533,11.0,22.025140,4.0,229533.0,2.0,2.757000e+11,1.0,NaN,131.832,31.62716,42.47333,36.76363
124429,54.0,57.465814,5.0,124429.0,2.0,3.471000e+11,3.0,NaN,142.349,46.15647,14.86934,17.27646
32879,34.0,6.711499,1.0,32879.0,3.0,6.806000e+11,2.0,NaN,178.168,1.89003,1.41235,41.26353
70495,42.0,9.285117,2.0,70495.0,3.0,6.004000e+11,2.0,NaN,170.878,0.73130,32.37007,36.46758
147062,40.0,20.475031,4.0,147062.0,3.0,9.168000e+11,2.0,NaN,196.767,32.61589,7.41276,46.25658
136254,26.0,43.093971,5.0,136254.0,3.0,6.725000e+11,2.0,NaN,177.456,42.29634,9.27925,33.19727
136001,51.0,6.285262,1.0,136001.0,4.0,1.046000e+12,3.0,NaN,205.599,28.64865,17.70496,23.64541
206312,38.0,9.624528,2.0,206312.0,4.0,1.083000e+12,2.0,NaN,207.991,42.55681,39.39494,2.92773
79392,42.0,14.885077,3.0,79392.0,4.0,1.086000e+12,2.0,NaN,208.227,4.27934,48.84792,3.93380
193602,47.0,21.004236,4.0,193602.0,4.0,1.013000e+12,2.0,NaN,203.393,30.68392,35.11199,39.08078
1330,23.0,36.327451,5.0,1330.0,4.0,1.012000e+12,1.0,NaN,203.332,0.76788,4.32026,0.06824
146616,79.0,5.738497,1.0,146616.0,5.0,3.470000e+12,4.0,NaN,306.646,44.75562,13.16332,46.09890
123930,57.0,10.037510,2.0,123930.0,5.0,3.941000e+12,3.0,NaN,319.943,23.56157,6.48661,21.87222
135915,63.0,20.494677,4.0,135915.0,5.0,2.435000e+12,3.0,NaN,272.482,45.70159,0.75919,23.11755
181619,45.0,35.297392,5.0,181619.0,5.0,2.224000e+12,2.0,NaN,264.378,20.55832,20.97311,33.76610
146457,118.0,12.961425,3.0,146457.0,6.0,4.977000e+12,5.0,NaN,345.827,40.70279,12.02742,48.07378
21720,70.0,21.487323,4.0,21720.0,6.0,6.339000e+12,3.0,NaN,374.865,12.77386,8.52803,32.86123
147804,23.0,6.502208,1.0,147804.0,1.0,1.072000e+11,1.0,1287.0,96.235,47.32173,12.74835,47.22086
124717,39.0,5.745947,1.0,124717.0,2.0,3.529000e+11,2.0,4700.0,143.141,42.78787,1.22517,18.37152
51769,27.0,11.875865,3.0,51769.0,3.0,6.017000e+11,2.0,7699.0,170.995,11.80620,31.80078,26.12099
157850,82.0,5.653106,1.0,157850.0,6.0,5.080000e+12,4.0,44818.0,348.185,39.63033,36.87334,9.74910
240613,168.0,8.774719,2.0,240613.0,6.0,6.771000e+12,5.0,78882.0,383.191,32.67094,41.52655,46.71777
193262,24.0,15.460119,3.0,193262.0,5.0,2.478000e+12,1.0,28200.0,274.083,46.70442,26.64880,46.60152